home:
   path: /
   controller: App\Infrastructure\Http\Web\Controller\UtilisateurController::index
   methods: [GET, POST]

# Routes for Example object
example_index:
    path: /example
    controller: App\Infrastructure\Http\Web\Controller\ExampleController::index
    methods: [GET]

example_new:
    path: /example/new
    controller: App\Infrastructure\Http\Web\Controller\ExampleController::new
    methods: [GET, POST]

example_show:
    path: /example/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\ExampleController::show
    methods: [GET, POST]

example_delete:
    path: /example/delete/{id}
    controller: App\Infrastructure\Http\Web\Controller\ExampleController::delete
    methods: [GET, POST]

# Routes for Fonction object
fonction_index:
    path: /fonction
    controller: App\Infrastructure\Http\Web\Controller\FonctionController::index
    methods: [GET]

fonction_new:
    path: /fonction/new
    controller: App\Infrastructure\Http\Web\Controller\FonctionController::new
    methods: [GET, POST]

fonction_show:
    path: /fonction/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\FonctionController::show
    methods: [GET, POST]

fonction_delete:
    path: /fonction/delete/{id}
    controller: App\Infrastructure\Http\Web\Controller\FonctionController::delete
    methods: [GET, POST]

# Routes for Role object
role_index:
    path: /role
    controller: App\Infrastructure\Http\Web\Controller\RoleController::index
    methods: [GET]

role_new:
    path: /role/new
    controller: App\Infrastructure\Http\Web\Controller\RoleController::new
    methods: [GET, POST]

role_show:
    path: /role/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\RoleController::show
    methods: [GET, POST]

role_delete:
    path: /role/delete/{id}
    controller: App\Infrastructure\Http\Web\Controller\RoleController::delete
    methods: [GET, POST]

    # Routes for Group object
group_index:
    path: /group
    controller: App\Infrastructure\Http\Web\Controller\GroupController::index
    methods: [GET]

group_new:
    path: /group/new
    controller: App\Infrastructure\Http\Web\Controller\GroupController::new
    methods: [GET, POST]

group_show:
    path: /group/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\GroupController::show
    methods: [GET, POST]

group_delete:
    path: /group/delete/{id}
    controller: App\Infrastructure\Http\Web\Controller\GroupController::delete
    methods: [GET, POST]
