App\Domain\Model\Company:
    type: entity
    table: company
    options:
        comment: Entité représentant un Company.

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique d'un company
    fields:
        name:
            type: string
            length: 191
            column: name
            nullable: false
        numSiret:
            type: string
            length: 14
            column: num_siret
            nullable: false
        urlName:
            type: string
            length: 100
            column: url_name
            nullable: false
    manyToOne:
        category:
            targetEntity: Category
            cascade: [persist]
            inversedBy: company
            joinColumn:
                name: id_category
                referencedColumnName: id
                nullable: false
        companystatut:
            targetEntity: CompanyStatut
            cascade: [persist]
            inversedBy: company
            joinColumn:
                name: id_companystatut
                referencedColumnName: id
                nullable: false
        city:
            targetEntity: City
            cascade: [persist]
            inversedBy: company
            joinColumn:
                name: id_city
                referencedColumnName: id
                nullable: false
    oneToOne:
        utilisateur:
            targetEntity: Utilisateur
            inversedBy: company
            joinColumn:
                name: utilisateur_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false
            cascade: [persist,remove]

        address:
            targetEntity: Address
            inversedBy: company
            joinColumn:
                name: id_address
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false
            cascade: [persist,remove]



